### ISSUE TITLE
Dialog content has incorrect tab-index

### ISSUE THREAD

**Issue by mwxxhdb** [ofajs/Punch-UI#48]
After dialog popup, click Tab key cannot focus in the input element in dialog content.

**Comment by kirakiray** [comment]
I tried it and it worked. Is there any specific case?

https://github.com/ofajs/Punch-UI/assets/5945154/522c105c-c6fe-442c-97a9-e4b28ea0d497

**Comment by kirakiray** [comment]
> https://ofajs.github.io/Punch-UI/packages/dialog/test-dialog.html
> 
> Click button `Open Dialog` and `Open List Dialog` in this page have the same issue.

Thank you for your reply. Your suggestion is very useful. We have changed it to focus on the form components in the pop-up window first. You can set [autofocus] to the component in the pop-up window as the first focused element
