### ISSUE TITLE
feature request: accordion component

### ISSUE THREAD

**Issue by mwxxhdb** [ofajs/Punch-UI#65]
I would like to learn how ofajs (web components) handle the case: one subcomponent affects the state of another subcomponent.

**Comment by kirakiray** [comment]
Sorry, I have been cleaning home for the past two days and read your feedback late.

There are two ways to modify the status of adjacent subcomponents:

One is that like Vue, subcomponents bubble up through events, and then modify the status of other subcomponents from the parent component. This method is more suitable for MVVM array binding situations.

```html
<!-- sub-item.html -->
<template component>
    <div>
        Sub Component 
        <slot></slot>
        <button on:click="changeOtherSub">Change Other Item</button>
    </div>
    <script>
        export default {
            tag:"sub-item",
            proto:{
                changeOtherSub(){
                    this.emit("change-others");
                }
            }
        };
    </script>
</template>
```

```html
<l-m src="./sub-item.html"></l-m>
<x-fill :value="arr">
    <sub-item on:change-others="$host.changeOthers($data,$index)">Sub Item {{$data.val}}</sub-item>
</x-fill>
<script>
    export default {
        data:{
            arr:[{val:1},{val:2},{val:3}]
        },
        proto:{
            changeOthers(data,index){
                // Additional sub-object data to process
                // const target = this.arr.find(e => xxxxxx)
                // target...
            }
        }
    };
</script>
```

The second method is to directly obtain adjacent elements to correct the state. The methods to obtain adjacent components include [siblings](https://ofajs.com/cn/api/instance/siblings.html), [next](https://ofajs.com/cn/api/instance/next.html), [nexts](https://ofajs.com/cn/api/instance/nexts.html), [prev](https://ofajs.com/cn/api/instance/prev.html), and [prevs](https://ofajs.com/cn/api/instance/prevs.html). Among them, siblings / nexts / prevs are used to obtain multiple adjacent elements, which are then traversed to modify the state. This method is suitable for correcting the state of components that are known to have business connections.


<template component>
    <div>
        Sub Component : {{somekey}}
        <slot></slot>
        <button on:click="changeOtherSub">Change Other Item</button>
    </div>
    <script>
        export default {
            tag:"sub-item",
            data:{
                somekey:1
            },
            proto:{
                changeOtherSub(){
                    this.siblings.forEach(item=>{
                        if(item.tag === "sub-item"){
                            item.somekey++;
                        }
                    });
                }
            }
        };
    </script>
</template>

You can also obtain and modify the state of the parent component through [parent](https://ofajs.com/cn/api/instance/parent.html) and [parents](https://ofajs.com/cn/api/instance/parents.html).

Here is a more complete case, including the following functions:
* Affect the style of subcomponents through styles
* Modify the status of child nodes
* Modify the status of adjacent nodes

[View Code](https://github1s.com/ofajs/test-cases/blob/main/affects-child-components/demo.html)

[View Online Demo](https://ofajs.github.io/test-cases/affects-child-components/demo.html)
